devopsMetadata/objects/Orgs__c.object
<CustomObject>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/objects/User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source</label>
        <referenceTo>Orgs__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <referenceTo>Orgs__c</referenceTo>
        <relationshipLabel>User Stories (Target)</relationshipLabel>
        <relationshipName>User_Stories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story_Name__c</fullName>
        <label>User Story Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{00000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/classes/TestDataFactory.cls
@isTest
public without sharing class TestDataFactory {
    public Orgs__c source{get;set;}
    public Orgs__c target{get;set;}
    public User_Story__c userStory{get;set;}
    public TestDataFactory() {
        source = new Orgs__c();
        source.Name = 'Dev1';
        source.Org_Type__c = 'Sandbox';
        insert source;
        target = new Orgs__c();
        target.Name = 'UAT';
        target.Org_Type__c = 'Sandbox';
        insert target;
        userStory = new User_Story__c();
        userStory.User_Story_Name__c = 'Test';
        userStory.Source__c = source.Id;
        userStory.Target__c = target.Id;
        insert userStory;
    }
}