devopsMetadata/objects/Pipeline__c.object
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/objects/Pipeline_Connection__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Orgs__c</referenceTo>
        <relationshipLabel>Pipeline Connections (Destination Environment)</relationshipLabel>
        <relationshipName>Pipeline_Target_Connections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pipeline for Connections</description>
        <label>Pipeline</label>
        <referenceTo>Pipeline__c</referenceTo>
        <relationshipLabel>Pipeline Connections</relationshipLabel>
        <relationshipName>Pipeline_Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Orgs__c</referenceTo>
        <relationshipLabel>Pipeline Connections</relationshipLabel>
        <relationshipName>Pipeline_Source_Connections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Pipeline Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline</label>
        <referenceTo>Pipeline__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/objects/User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User Story Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source</label>
        <referenceTo>Orgs__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <referenceTo>Orgs__c</referenceTo>
        <relationshipLabel>User Stories (Target)</relationshipLabel>
        <relationshipName>User_Stories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{00000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/classes/UserStoryTriggerHandler.cls
public class UserStoryTriggerHandler {
    public static void updateTargetOrg(List<User_Story__c> userStories) {
        for(User_Story__c userStory : userStories) {
            List<Pipeline_Connection__c> connections = [select Id,Source_Environment__c,Destination_Environment__c from Pipeline_Connection__c where Pipeline__c =: userStory.Project__r.Pipeline__r.Id];
            for(Pipeline_Connection__c connection : connections) {
                if(connection.Source_Environment__c == userStory.Source__c) {
                    userStory.Target__c = connection.Destination_Environment__c;
                    break;
                }
            }
        }
    }
}