devopsMetadata/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Progress__c</fullName>
        <label>Progress</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Project</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devopsMetadata/objects/Sprint__c.object
<CustomObject>
    <description>Sprint of Project</description>
    <fields>
        <fullName>Progress__c</fullName>
        <description>Progress of Sprint</description>
        <label>Progress</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Sprint</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

devopsMetadata/classes/LwcChartController.cls
/**
	* This class is used to generate dataset for lwc charts.
*/
public class LwcChartController {
	@AuraEnabled(cacheable=true)
    public static List<DataSet> getProjectSprints(String projectId){
        DateTime todayDate ;
        Timezone tz = Timezone.getTimeZone('America/Los_Angeles');
        Datetime pst_Date = DateTime.newInstance(System.Now().getTime() + tz.getOffset(System.Now()));
        todayDate = pst_Date.date().addDays(-1);
        
        List<Sprint__c> sprints =  [SELECT Name,Progress__c,Status__c  FROM Sprint__c WHERE Project__c =: projectId];
        List<DataSet> dataSet = new List<DataSet>();
        for(Sprint__c sprint : sprints){
            String name =  (String)sprint.get('Name') ;
            //String status =  (String)sprint.get('Status__c') ;
            Decimal total =  (Decimal)sprint.get('Progress__c') ;
            dataSet.add(new DataSet(name,total));
        }
        System.debug('dataSet'+dataSet);
        return dataSet ;
    }
    
    public class DataSet{
        @AuraEnabled
        public String label {get;set;}
        @AuraEnabled
        public String status {get;set;}
        @AuraEnabled
        public Decimal count {get;set;}
        
        public DataSet(String label,Decimal count){
            this.label  = label ;
            this.count = count ;
        }
        public DataSet(String label,Decimal count,String status){
            this.label  = label ;
            this.count = count ;
            this.status = status;
        }
    }
}